### ISSUE TITLE
create a new directory inside the output dir before download starts

### ISSUE THREAD

**Issue by kcsomisetty** [Kanishkduggi/iArchive#1]
current behavior:
the current script downloads the files directly to the output directory.

expected behavior:
create a directory inside the output dir and download the contents to that directory.

**Comment by Kanishkduggi** [comment]
web scrapping is something very new to me this is the code which i have reffered various resources and yt channels.i pushed an new file named as IArchive_newqueries in which you will get the solution of the two queries
