### ISSUE TITLE
download of second image fails

### ISSUE THREAD

**Issue by kcsomisetty** [Kanishkduggi/iArchive#2]
run the script on this url
https://timesofindia.indiatimes.com/india/naidu-seeks-report-on-tirupati-laddus-dont-politicise-jagan/articleshow/113538895.cms

2 images should be downloaded, but only one is shown in images folder.

**Comment by Kanishkduggi** [comment]
this might be because of the lazy loading of the website this can be mittigated by small correction in the code  to check for image attributes and changed some part of the code
