### ISSUE TITLE
Open a downloaded page.

### ISSUE THREAD

**Issue by kcsomisetty** [Kanishkduggi/iArchive#3]
1. download this url
2. open the downloaded page

observed behavior:
1. opened page appears for a while and bcomes blank
2. probably because of some script that failed to load or loads and than blanks the page.

**Comment by Kanishkduggi** [comment]
one of the main problem is external scripts that is Some pages load scripts from external servers, and if those scripts fail to load or execute when opening the saved page locally, the page can go blank. so to eradicate this issue we are now using a new method using selenium where it can  now be open the downloaded with minimum latency and does not become blank
the code for the 2 issues are attached as Iarchive_updated
