### ISSUE TITLE
Create a new Archive script which takes a screentshot of the webpage

### ISSUE THREAD

**Issue by kcsomisetty** [Kanishkduggi/iArchive#4]
instead of downloading the html content, take a screenshot of the page and save it to disk.

**Comment by Kanishkduggi** [comment]
here we are going to use a new tool called as selenium in which we are taking a screenshot .selenium is a open source tool where we can web scrape which uses dynamic approach where the content is extracted.
we are supposed to download the selenium in your terminal to run the code.
